name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NEXT_PUBLIC_BASE_PATH: "/adovo-fe"
  NEXT_PUBLIC_ASSETS_PATH: "/adovo-fe/assets"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "install_cmd=yarn install --frozen-lockfile" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
            echo "cache_dir=$(yarn cache dir)" >> $GITHUB_ENV
          elif [ -f "package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "install_cmd=npm ci" >> $GITHUB_ENV
            echo "runner=npx --no-install" >> $GITHUB_ENV
            echo "cache_dir=$(npm config get cache)" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ env.manager }}

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ${{ env.cache_dir }}
          key: ${{ runner.os }}-${{ env.manager }}-${{ hashFiles('package-lock.json', 'yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.manager }}-

      - name: Install dependencies
        run: ${{ env.install_cmd }}

      - name: Set up environment variables
        run: |
          echo "NEXT_PUBLIC_BASE_PATH=/adovo-fe" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_ASSETS_PATH=/adovo-fe/assets" >> $GITHUB_ENV

      - name: Configure Next.js for GitHub Pages
        run: |
          echo "module.exports = {
            eslint: { ignoreDuringBuilds: true },
            output: 'export',
            basePath: process.env.NEXT_PUBLIC_BASE_PATH,
            assetPrefix: process.env.NEXT_PUBLIC_BASE_PATH,
            images: { unoptimized: true },
            trailingSlash: true
          };" > next.config.js

      - name: Build with Next.js (Skipping ESLint)
        run: NEXT_PUBLIC_DISABLE_ESLINT=true NEXT_PUBLIC_BASE_PATH=/adovo-fe NEXT_PUBLIC_ASSETS_PATH=/adovo-fe/assets ${{ env.runner }} next build


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
